/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'canon-edsdk.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.android-arm64.node')
          } else {
            nativeBinding = require('canon-edsdk-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'canon-edsdk.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.android-arm-eabi.node')
          } else {
            nativeBinding = require('canon-edsdk-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'canon-edsdk.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.win32-x64-msvc.node')
          } else {
            nativeBinding = require('canon-edsdk-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'canon-edsdk.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('canon-edsdk-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'canon-edsdk.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('canon-edsdk-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'canon-edsdk.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./canon-edsdk.darwin-universal.node')
      } else {
        nativeBinding = require('canon-edsdk-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'canon-edsdk.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.darwin-x64.node')
          } else {
            nativeBinding = require('canon-edsdk-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'canon-edsdk.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.darwin-arm64.node')
          } else {
            nativeBinding = require('canon-edsdk-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'canon-edsdk.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./canon-edsdk.freebsd-x64.node')
      } else {
        nativeBinding = require('canon-edsdk-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-x64-musl.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-x64-gnu.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-arm64-musl.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'canon-edsdk.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./canon-edsdk.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('canon-edsdk-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'canon-edsdk.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./canon-edsdk.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('canon-edsdk-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { getPropertyIds, getShutterButton, initializeSdk, terminateSdk, isSdkInitializedCheck, getSdkVersion, getEdsdkDllPath, getCameraList, connectCamera, connectCameraByIndex, openSession, closeSession, disconnectCamera, isCameraConnected, isSessionOpen, takePicture, captureToBuffer, pressShutterButton, startLiveView, stopLiveView, getLiveViewFrame, getProperty, setProperty, getIso, setIso, getAperture, setAperture, getShutterSpeed, setShutterSpeed, getBatteryLevel, getAvailableShots, processEvents } = nativeBinding

module.exports.getPropertyIds = getPropertyIds
module.exports.getShutterButton = getShutterButton
module.exports.initializeSdk = initializeSdk
module.exports.terminateSdk = terminateSdk
module.exports.isSdkInitializedCheck = isSdkInitializedCheck
module.exports.getSdkVersion = getSdkVersion
module.exports.getEdsdkDllPath = getEdsdkDllPath
module.exports.getCameraList = getCameraList
module.exports.connectCamera = connectCamera
module.exports.connectCameraByIndex = connectCameraByIndex
module.exports.openSession = openSession
module.exports.closeSession = closeSession
module.exports.disconnectCamera = disconnectCamera
module.exports.isCameraConnected = isCameraConnected
module.exports.isSessionOpen = isSessionOpen
module.exports.takePicture = takePicture
module.exports.captureToBuffer = captureToBuffer
module.exports.pressShutterButton = pressShutterButton
module.exports.startLiveView = startLiveView
module.exports.stopLiveView = stopLiveView
module.exports.getLiveViewFrame = getLiveViewFrame
module.exports.getProperty = getProperty
module.exports.setProperty = setProperty
module.exports.getIso = getIso
module.exports.setIso = setIso
module.exports.getAperture = getAperture
module.exports.setAperture = setAperture
module.exports.getShutterSpeed = getShutterSpeed
module.exports.setShutterSpeed = setShutterSpeed
module.exports.getBatteryLevel = getBatteryLevel
module.exports.getAvailableShots = getAvailableShots
module.exports.processEvents = processEvents

// Compatibility aliases for bonio-booth
module.exports.isSdkInitialized = isSdkInitializedCheck
module.exports.propertyIds = getPropertyIds()
module.exports.shutterButton = getShutterButton()
